### ISSUE TITLE
remotecv-web broken

### ISSUE THREAD

**Issue by gi11es** [thumbor/remotecv#12]
`gilles@thumbor:~/thumbor-debian/remotecv/remotecv-2.2.1/debian$ remotecv-web
Traceback (most recent call last):
  File "/usr/bin/remotecv-web", line 9, in <module>
    load_entry_point('remotecv==2.2.1', 'console_scripts', 'remotecv-web')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/remotecv/web.py", line 18, in <module>
    from resweb import server as resweb_server
ImportError: cannot import name server`

it would appear there is no "server" in the current version of resweb: https://github.com/Pyres/resweb/tree/master/resweb

Maybe remotecv-web dates back to when resweb was still part of pyres and wasn't flask-based? This would suggest so: https://github.com/binarydud/pyres/blob/1.0/resweb/server.py

The fix doesn't seem to be too complicated, the host override just has to be pointed to the new location. But I don't know if that will make remotecv-web truly work. And for that matter, is remotecv-web still relevant and used?

**Comment by gi11es** [comment]
I see that fixing remotecv-web is a bit more involved: resweb is now based on flask, not itty. Which means that override and start method have to be different.

**Comment by guilhermef** [comment]
We should be remove resweb from remotecv, and run it standalone

**Comment by gi11es** [comment]
Right, all remotecv-web does is run resweb with specific parameters, correct?

**Comment by guilhermef** [comment]
That's correct
Em 07/06/2016 08:18, "Gilles Dubuc" <notifications@github.com> escreveu:
