### ISSUE TITLE
Avoid version limitations?

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/remotecv#15]
Hi,

I would like to package remotecv as RPM for CentOS7 distribution, like I did with Thumbor. Unfortunately, the project uses specific version dependencies, which might be a roadblock for possible security fixes that might arise into future. I think the queued detection is very cool and beneficial for large scale Thumbor setups which use Redis as storage backend.

Is there a way to update the project and remove the dependencies which does not allows us use the latest versions of python-redis, python-pyres and python-argparse?

Regards,

Floren

**Comment by nbouvrette** [comment]
Agreed with @fmunteanu, we should be able to use recent versions to avoid security issues.

**Comment by gingerlime** [comment]
Any updates on this one? (It's been open for over a year ...). I wonder if there's any *actual* reason to limit to those versions? I imagine all of those libs (including redis itself) are fairly backwards compatible

**Comment by scorphus** [comment]
Fixed by #43
