### ISSUE TITLE
remotecv multiprocess

### ISSUE THREAD

**Issue by eduherraiz** [thumbor/remotecv#4]
We have a working docker images including remotecv working here:
https://github.com/APSL/docker-thumbor

I'm doing a v2 of this images trying to improve the performance and docker architecture.
In the old architecture, we keep a unique docker container executing a unique remotecv process.
What do you think about the possibility to have multiple remotecv processes running with the same redis configuration?
I'm considering the opportunity to scale up the remotecv service by this way and I can't found any reference in the documentation.

**Comment by masom** [comment]
Depending on the queue it should be safe to have several thumbor instances talking to several remotecv instances.

**Comment by eduherraiz** [comment]
Nice! I will prepare the docker with this in mind. :-D

**Comment by masom** [comment]
@eduherraiz Better test it first :)

Given Redis queues ( or SQS , Gearman, etc. ) it is usually possible to run multiple consumers (remotecv) and have multiple producers  ( thumbor )

**Comment by eduherraiz** [comment]
@masom , of course I will test it. 

I don't have any doubt about redis, I want to know if remotecv is able to manage the concurrency problems associated with the thumbor's queue.
I'm worried about how to manage the processing images with multiple remotecv processes with one queue.

**Comment by eduherraiz** [comment]
I tested today and works properly. Multiple remotecv processes can work with same redis queue, sharing the load. :+1:
