### ISSUE TITLE
Getting 403 errors with RemoteCV

### ISSUE THREAD

**Issue by assembledadam** [thumbor/remotecv#6]
Turns out that there's quite a lot of servers blocking requests for content by bots (as identified by the user agent).  It appears remoteCV is utilising Python-urllib for retrieving images - specifically in my case 'Python-urllib/2.7'. 

E.g. Cloudflare has this in it's default list whenever the panel is set to reject requests from bots. Causing me quite a few pains at the moment.

Solution: can we bake in some config option to remoteCV/thumbor to alter the user agent?  I see it exists for the thumbor's http loader but not the detector's loader.

I can have a crack but I've written almost nothing in Python before so will take me a little longer!

Thanks

**Comment by assembledadam** [comment]
Actually the actual code change is fairly trivial - it's just the config management that needs some thought... any ideas on a good approach?

In remotecv/http_loader.py, replace:
```
return urllib2.urlopen(path).read()
```
with:
```
req = urllib2.Request(path, headers={ USER_AGENT_STRING })
return urllib2.urlopen(req).read()
```

**Comment by guilhermef** [comment]
@assembledadam You can use your own loader to avoid these errors, you just have to pass on the remotecv worker command line a -o 'my_package.http_loader'

**Comment by assembledadam** [comment]
Never used python before so trying to figure out a lot of things...

Can I just make it a 'module', i.e. a singly py file and reference that?  If so where does it have to be located to be found from that command?

**Comment by guilhermef** [comment]
sure, you can copy the current http_loader.py and change things.
Then you just start your worker with:
```
$PYTHONPATH=/my/module/path:$PYTHONPATH start_worker
```

**Comment by assembledadam** [comment]
It needs to be discoverable relatively.  So my use case:

I've forked https://github.com/APSL/docker-thumbor so that I can edit the docker remotecv invocation script (https://github.com/assembledadam/docker-thumbor/blob/master/remotecv/docker-entrypoint.sh).

In the setup (https://github.com/assembledadam/docker-thumbor/blob/master/remotecv/Dockerfile), the docker-entrypoint.sh script is copied as well as a directory called 'loaders'.  Inside 'loaders' is ```__init__.py``` (blank) and ```http_loader.py``` which contains the modified code (and I think this makes it a python package?).

So the 'loaders' directory/package should be in the same directory as the docker-entrypoint.sh script.

So the command run is 
````
exec remotecv --host $REDIS_HOST --port $REDIS_PORT --database $REDIS_DATABASE -l $LOG_LEVEL -o loaders.http_loader
````

Problem is, I'm getting 
```
remotecv_1 | Traceback (most recent call last):
remotecv_1 |   File "/usr/local/bin/remotecv", line 9, in <module>
remotecv_1 |     load_entry_point('remotecv==1.0.2', 'console_scripts', 'remotecv')()
remotecv_1 |   File "/usr/local/lib/python2.7/site-packages/remotecv/worker.py", line 88, in main
remotecv_1 |     config.loader = import_module(arguments.loader)
remotecv_1 |   File "/usr/local/lib/python2.7/site-packages/remotecv/worker.py", line 21, in import_module
remotecv_1 |     module = __import__(name)
remotecv_1 | ImportError: No module named loaders.http_loader
```

Any ideas?

**Comment by guilhermef** [comment]
You can add a new path to your PYTHONPATH using an environment variable.
```
$PYTHONPATH=/my/module/path:$PYTHONPATH start_worker

**Comment by assembledadam** [comment]
I understand that I can add the path there, but what is the start_worker part for?

It will be initialised with the remotecv command above...

**Comment by guilhermef** [comment]
start_worker is just a placeholder for your worker command, in this case, remotecv

**Comment by assembledadam** [comment]
Is there no way it can be discoverable relatively? Your example is still an absolute path.

**Comment by guilhermef** [comment]
You can use:
```
$PYTHONPATH=.:$PYTHONPATH remotecv
```
Then you will add the current pwd to your PYTHONPATH

**Comment by assembledadam** [comment]
Not having much luck here.

That doesn't appear to be valid bash.
```zsh: .: not found```

If I take away the $ so it's a valid bash variable  ```exec PYTHONPATH=".:$PYTHONPATH"``` I just get:
```
remotecv_1 | /docker-entrypoint.sh: line 10: exec: PYTHONPATH=.:: not found
```

**Comment by guilhermef** [comment]
I think it should be like this
```
#!/bin/bash
set -e

[[ -z $REDIS_HOST ]] && REDIS_HOST=redis
[[ -z $REDIS_PORT ]] && REDIS_PORT=6379
[[ -z $REDIS_DATABASE ]] && REDIS_DATABASE=0
[[ -z $LOG_LEVEL ]] && LOG_LEVEL=INFO

if [ "$1" = 'remotecv' ]; then
    PYTHONPATH=.:$PYTHONPATH exec remotecv --host $REDIS_HOST --port $REDIS_PORT --database $REDIS_DATABASE -l $LOG_LEVEL -o loaders.http_loader
fi

exec "$@"

**Comment by assembledadam** [comment]
Still no joy.  I checked the directory is in the right place and that PYTHONPATH is set to .: and all looks fine, but still getting
```
remotecv_1 | Traceback (most recent call last):
remotecv_1 |   File "/usr/local/bin/remotecv", line 9, in <module>
remotecv_1 |     load_entry_point('remotecv==1.0.2', 'console_scripts', 'remotecv')()
remotecv_1 |   File "/usr/local/lib/python2.7/site-packages/remotecv/worker.py", line 88, in main
remotecv_1 |     config.loader = import_module(arguments.loader)
remotecv_1 |   File "/usr/local/lib/python2.7/site-packages/remotecv/worker.py", line 21, in import_module
remotecv_1 |     module = __import__(name)
remotecv_1 | ImportError: No module named loaders.http_loader
```

So presumably my structure is correct?
```
.
..
/loaders
    __init__.py
    http_loader.py
    docker-entrypoint.sh
```

**Comment by guilhermef** [comment]
That's right, It should work.

**Comment by assembledadam** [comment]
It doesn't.  Any idea why it couldn't be finding it?  Is there any other way it can find it?

**Comment by guilhermef** [comment]
Sure, you can create a python package and install it, then it will be on your site-package.

**Comment by assembledadam** [comment]
As I understand it I have already made a package (the folder with the __init__ file), but I guess you mean make an installable package.  No idea how to do this.

Googling reveals this as a decent resource: https://python-packaging.readthedocs.org/en/latest/

Is that what you mean? Thanks.

**Comment by assembledadam** [comment]
Ok - finally got it working. Thank you for your help!

**Comment by alexandernst** [comment]
But why not just merge that option instead of making us implement our own loader? It surely sounds like work duplication.
