### ISSUE TITLE
Switch to YuNet face detection model

### ISSUE THREAD

**Issue by guilhermef** [thumbor/remotecv#69]
According to the benchmark, the YuNet model can detect more faces, and it's consistently faster than the current model used by RemoteCV and Thumbor.

https://opencv.org/opencv-face-detection-cascade-classifier-vs-yunet/

https://github.com/opencv/opencv_zoo/tree/master/models/face_detection_yunet

**Comment by RaphaelVRossi** [comment]
Nice catch @guilhermef  🥳
